package com.foody.wallet;
import static org.assertj.core.api.Assertions.*;
import com.foody.AbstractContainerBaseTest; import com.foody.businesses.entity.*; import com.foody.businesses.repository.BusinessRepository;
import com.foody.common.exception.*; import com.foody.users.entity.*; import com.foody.users.repository.UserRepository;
import com.foody.wallet.dto.*; import com.foody.wallet.entity.*; import com.foody.wallet.repository.*; import com.foody.wallet.service.WalletService;
import java.math.BigDecimal; import java.util.*; import java.util.concurrent.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired;
class WalletIntegrationTest extends AbstractContainerBaseTest {
 @Autowired WalletService service; @Autowired UserRepository users; @Autowired BusinessRepository businesses; @Autowired WalletRepository wallets; @Autowired WalletTransactionRepository txs;
 User customer,other,owner1,owner2,admin; Business cafe1,cafe2;
 @BeforeEach void setUp(){customer=user(UserRole.CUSTOMER);other=user(UserRole.CUSTOMER);owner1=user(UserRole.BUSINESS_OWNER);owner2=user(UserRole.BUSINESS_OWNER);admin=user(UserRole.ADMIN);cafe1=business(owner1);cafe2=business(owner2);}
 @Test void sameCustomerHasSeparateBalancesAcrossBusinesses(){service.ownerCredit(owner1.getId(),customer.getId(),bd("200000"));service.ownerCredit(owner2.getId(),customer.getId(),bd("50000"));assertThat(service.customerWallets(customer.getId())).extracting(WalletResponse::balance).containsExactlyInAnyOrder(bd("200000.00"),bd("50000.00"));}
 @Test void ownerCreditsOnlyOwnBusiness(){WalletResponse w=service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));assertThat(w.businessId()).isEqualTo(cafe1.getId());assertThat(w.balance()).isEqualByComparingTo("10");}
 @Test void ownerCannotTargetAnotherOwnersWallet(){service.ownerCredit(owner2.getId(),customer.getId(),bd("8"));service.ownerCredit(owner1.getId(),customer.getId(),bd("3"));service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("2"));assertThat(wallets.findByCustomerUserIdAndBusinessId(customer.getId(),cafe2.getId()).orElseThrow().getBalance()).isEqualByComparingTo("8");}
 @Test void debitRequestDoesNotImmediatelyChangeBalance(){WalletResponse w=service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));assertThat(wallets.findById(w.id()).orElseThrow().getBalance()).isEqualByComparingTo("10");}
 @Test void correctCustomerApprovesAndLedgerRecordsOwner(){service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));assertThat(service.approve(customer.getId(),r.id()).status()).isEqualTo(DebitRequestStatus.APPROVED);WalletResponse w=service.customerWallets(customer.getId()).getFirst();assertThat(w.balance()).isEqualByComparingTo("6");assertThat(service.customerTransactions(customer.getId(),w.id()).getFirst()).extracting(WalletTransactionResponse::type,WalletTransactionResponse::actorUserId).containsExactly(WalletTransactionType.OWNER_DEBIT,owner1.getId());}
 @Test void anotherCustomerCannotApprove(){DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("1"));assertThatThrownBy(()->service.approve(other.getId(),r.id())).isInstanceOf(ResourceNotFoundException.class);}
 @Test void rejectionDoesNotChangeBalance(){WalletResponse w=service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));service.reject(customer.getId(),r.id());assertThat(wallets.findById(w.id()).orElseThrow().getBalance()).isEqualByComparingTo("10");}
 @Test void approvedRequestCannotBeApprovedTwice(){service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));service.approve(customer.getId(),r.id());assertThatThrownBy(()->service.approve(customer.getId(),r.id())).isInstanceOf(InvalidStateTransitionException.class);}
 @Test void insufficientBalanceApprovalFailsAndRemainsPending(){DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));assertThatThrownBy(()->service.approve(customer.getId(),r.id())).isInstanceOf(InsufficientBalanceException.class);assertThat(service.pendingRequests(customer.getId())).extracting(DebitRequestResponse::id).contains(r.id());}
 @Test void adminCreditIsImmediate(){assertThat(service.adminCredit(admin.getId(),customer.getId(),cafe1.getId(),bd("7")).balance()).isEqualByComparingTo("7");}
 @Test void adminDebitIsImmediate(){service.adminCredit(admin.getId(),customer.getId(),cafe1.getId(),bd("7"));assertThat(service.adminDebit(admin.getId(),customer.getId(),cafe1.getId(),bd("2")).balance()).isEqualByComparingTo("5");assertThat(service.pendingRequests(customer.getId())).isEmpty();}
 @Test void adminDebitCannotMakeBalanceNegative(){assertThatThrownBy(()->service.adminDebit(admin.getId(),customer.getId(),cafe1.getId(),bd("1"))).isInstanceOf(InsufficientBalanceException.class);}
 @Test void concurrentApprovalCannotDoubleDebit() throws Exception {service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("4"));ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);Callable<Boolean> task=()->{start.await();try{service.approve(customer.getId(),r.id());return true;}catch(InvalidStateTransitionException e){return false;}};Future<Boolean>a=pool.submit(task),b=pool.submit(task);start.countDown();assertThat(List.of(a.get(10,TimeUnit.SECONDS),b.get(10,TimeUnit.SECONDS))).containsExactlyInAnyOrder(true,false);pool.shutdownNow();assertThat(service.customerWallets(customer.getId()).getFirst().balance()).isEqualByComparingTo("6");}
 @Test void everySuccessfulBalanceChangeCreatesLedger(){WalletResponse w=service.ownerCredit(owner1.getId(),customer.getId(),bd("10"));DebitRequestResponse r=service.ownerRequestDebit(owner1.getId(),customer.getId(),bd("2"));service.approve(customer.getId(),r.id());service.adminCredit(admin.getId(),customer.getId(),cafe1.getId(),bd("3"));service.adminDebit(admin.getId(),customer.getId(),cafe1.getId(),bd("1"));assertThat(txs.findByWalletIdOrderByCreatedAtDesc(w.id())).hasSize(4).extracting(WalletTransaction::getType).containsExactlyInAnyOrder(WalletTransactionType.OWNER_CREDIT,WalletTransactionType.OWNER_DEBIT,WalletTransactionType.ADMIN_CREDIT,WalletTransactionType.ADMIN_DEBIT);}
 private BigDecimal bd(String v){return new BigDecimal(v);} private User user(UserRole role){User u=new User();u.setEmail(UUID.randomUUID()+"@wallet.test");u.setFullName("Wallet test");u.setPasswordHash("unused");u.setRole(role);return users.saveAndFlush(u);} private Business business(User owner){Business b=new Business();b.setOwnerUserId(owner.getId());b.setName("Cafe "+UUID.randomUUID());b.setBusinessType("CAFE");b.setStatus(BusinessStatus.APPROVED);return businesses.saveAndFlush(b);}
}
