package com.foody.communications.service;
import com.foody.businesses.entity.Business; import com.foody.businesses.repository.BusinessRepository; import com.foody.common.exception.*; import com.foody.communications.dto.*; import com.foody.communications.entity.*; import com.foody.communications.repository.*; import com.foody.notifications.entity.NotificationType; import com.foody.notifications.service.NotificationService; import com.foody.users.entity.*; import com.foody.users.repository.UserRepository; import java.time.Instant; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class CommunicationServiceImpl implements CommunicationService {
 private final SupportTicketRepository tickets; private final SupportTicketMessageRepository ticketMessages; private final BusinessMessageRepository messages; private final BusinessMessageReadRepository reads; private final BusinessRepository businesses; private final UserRepository users; private final NotificationService notifications;
 CommunicationServiceImpl(SupportTicketRepository t,SupportTicketMessageRepository tm,BusinessMessageRepository m,BusinessMessageReadRepository r,BusinessRepository b,UserRepository u,NotificationService n){tickets=t;ticketMessages=tm;messages=m;reads=r;businesses=b;users=u;notifications=n;}
 @Transactional public CommunicationResponses.TicketDetail createTicket(Long ownerId,CommunicationRequests.CreateTicket request){Business b=ownerBusiness(ownerId);SupportTicket t=new SupportTicket();t.setBusinessId(b.getId());t.setOwnerUserId(ownerId);t.setSubject(text(request.subject(),160,"Subject"));t.setOwnerLastReadAt(Instant.now());t=tickets.saveAndFlush(t);addReply(t,ownerId,CommunicationSenderType.BUSINESS_OWNER,request.message());notifyAdmins("درخواست پشتیبانی جدید",b.getName()+": "+t.getSubject(),t.getId());return detail(t,false);}
 @Transactional(readOnly=true) public CommunicationResponses.Page<CommunicationResponses.TicketSummary> ownerTickets(Long ownerId,int page,int limit){Business b=ownerBusiness(ownerId);var slice=tickets.findByBusinessIdOrderByUpdatedAtDesc(b.getId(),page(page,limit));return ticketPage(slice,false);}
 @Transactional public CommunicationResponses.TicketDetail ownerTicket(Long ownerId,Long ticketId){SupportTicket t=ownTicket(ownerId,ticketId);t.setOwnerLastReadAt(Instant.now());tickets.save(t);return detail(t,false);}
 @Transactional public CommunicationResponses.TicketDetail ownerReply(Long ownerId,Long ticketId,CommunicationRequests.Reply request){SupportTicket t=ownTicket(ownerId,ticketId);ensureOpen(t);addReply(t,ownerId,CommunicationSenderType.BUSINESS_OWNER,request.message());t.setStatus(TicketStatus.OPEN);t.setOwnerLastReadAt(Instant.now());t.setAdminLastReadAt(null);tickets.saveAndFlush(t);notifyAdmins("پاسخ جدید کسب‌وکار",business(t.getBusinessId()).getName()+": "+t.getSubject(),t.getId());return detail(t,false);}
 @Transactional(readOnly=true) public CommunicationResponses.Page<CommunicationResponses.BusinessMessageView> ownerMessages(Long ownerId,int page,int limit){Business b=ownerBusiness(ownerId);var slice=messages.inbox(b.getId(),page(page,limit));List<Long> messageIds=slice.getContent().stream().map(BusinessMessage::getId).toList();Set<Long> readIds=messageIds.isEmpty()?Set.of():reads.findByBusinessIdAndMessageIdIn(b.getId(),messageIds).stream().map(BusinessMessageRead::getMessageId).collect(Collectors.toSet());return new CommunicationResponses.Page<>(slice.getContent().stream().map(m->messageView(m,readIds.contains(m.getId()))).toList(),page,slice.hasNext());}
 @Transactional public CommunicationResponses.BusinessMessageView ownerMessage(Long ownerId,Long messageId){Business b=ownerBusiness(ownerId);BusinessMessage m=messages.findVisible(messageId,b.getId()).orElseThrow(()->new ResourceNotFoundException("Message not found"));BusinessMessageReadId id=new BusinessMessageReadId(m.getId(),b.getId());if(!reads.existsById(id)){BusinessMessageRead r=new BusinessMessageRead();r.setMessageId(m.getId());r.setBusinessId(b.getId());reads.save(r);}return messageView(m,true);}
 @Transactional(readOnly=true) public CommunicationResponses.UnreadCount ownerUnread(Long ownerId){Business b=ownerBusiness(ownerId);long messageCount=messages.countUnread(b.getId());long ticketCount=tickets.findByBusinessIdOrderByUpdatedAtDesc(b.getId(),Pageable.unpaged()).stream().filter(t->ownerUnread(t)).count();return new CommunicationResponses.UnreadCount(messageCount+ticketCount);}
 @Transactional(readOnly=true) public CommunicationResponses.Page<CommunicationResponses.TicketSummary> adminTickets(TicketStatus status,int page,int limit){var p=page(page,limit);var slice=status==null?tickets.findAllByOrderByUpdatedAtDesc(p):tickets.findByStatusOrderByUpdatedAtDesc(status,p);return ticketPage(slice,true);}
 @Transactional public CommunicationResponses.TicketDetail adminTicket(Long adminId,Long ticketId){SupportTicket t=ticket(ticketId);t.setAdminLastReadAt(Instant.now());tickets.save(t);return detail(t,true);}
 @Transactional public CommunicationResponses.TicketDetail adminReply(Long adminId,Long ticketId,CommunicationRequests.Reply request){SupportTicket t=ticket(ticketId);ensureOpen(t);addReply(t,adminId,CommunicationSenderType.ADMIN,request.message());t.setStatus(TicketStatus.ANSWERED);t.setAdminLastReadAt(Instant.now());t.setOwnerLastReadAt(null);tickets.saveAndFlush(t);return detail(t,true);}
 @Transactional public CommunicationResponses.TicketDetail closeTicket(Long adminId,Long ticketId){SupportTicket t=ticket(ticketId);if(t.getStatus()==TicketStatus.CLOSED)throw new InvalidRequestException("Ticket is already closed");t.setStatus(TicketStatus.CLOSED);t.setAdminLastReadAt(Instant.now());tickets.saveAndFlush(t);return detail(t,true);}
 @Transactional public CommunicationResponses.BusinessMessageView sendDirect(Long adminId,CommunicationRequests.DirectMessage request){Business b=business(request.businessId());BusinessMessage m=new BusinessMessage();m.setTargetBusinessId(b.getId());m.setSenderAdminUserId(adminId);m.setMessageType(BusinessMessageType.DIRECT);m.setSubject(text(request.subject(),160,"Subject"));m.setBody(text(request.message(),4000,"Message"));m=messages.saveAndFlush(m);return messageView(m,false);}
 @Transactional public CommunicationResponses.BusinessMessageView sendBroadcast(Long adminId,CommunicationRequests.Broadcast request){BusinessMessage m=new BusinessMessage();m.setSenderAdminUserId(adminId);m.setMessageType(BusinessMessageType.BROADCAST);m.setAudienceBusinessIdCutoff(businesses.maxId());m.setSubject(text(request.subject(),160,"Subject"));m.setBody(text(request.message(),4000,"Message"));return messageView(messages.saveAndFlush(m),false);}
 @Transactional(readOnly=true) public CommunicationResponses.Page<CommunicationResponses.BusinessMessageView> sentMessages(int page,int limit){var slice=messages.findAllByOrderByCreatedAtDesc(page(page,limit));return new CommunicationResponses.Page<>(slice.getContent().stream().map(m->messageView(m,false)).toList(),page,slice.hasNext());}
 private CommunicationResponses.Page<CommunicationResponses.TicketSummary> ticketPage(Slice<SupportTicket>s,boolean admin){return new CommunicationResponses.Page<>(s.getContent().stream().map(t->summary(t,admin)).toList(),s.getNumber(),s.hasNext());}
 private CommunicationResponses.TicketDetail detail(SupportTicket t,boolean admin){List<SupportTicketMessage> persisted=ticketMessages.findByTicketIdOrderByCreatedAtAscIdAsc(t.getId());Map<Long,User> senders=users.findAllById(persisted.stream().map(SupportTicketMessage::getSenderUserId).collect(Collectors.toSet())).stream().collect(Collectors.toMap(User::getId,Function.identity()));List<CommunicationResponses.TicketMessage> ms=persisted.stream().map(m->new CommunicationResponses.TicketMessage(m.getId(),m.getSenderType(),senders.get(m.getSenderUserId()).getFullName(),m.getBody(),m.getCreatedAt())).toList();return new CommunicationResponses.TicketDetail(summary(t,admin),ms);}
 private CommunicationResponses.TicketSummary summary(SupportTicket t,boolean admin){Business b=business(t.getBusinessId());User owner=users.findById(t.getOwnerUserId()).orElseThrow();return new CommunicationResponses.TicketSummary(t.getId(),b.getId(),b.getName(),owner.getFullName(),t.getSubject(),t.getStatus(),admin?adminUnread(t):ownerUnread(t),t.getCreatedAt(),t.getUpdatedAt());}
 private boolean ownerUnread(SupportTicket t){return t.getStatus()==TicketStatus.ANSWERED&&t.getOwnerLastReadAt()==null;} private boolean adminUnread(SupportTicket t){return t.getStatus()==TicketStatus.OPEN&&t.getAdminLastReadAt()==null;}
 private CommunicationResponses.BusinessMessageView messageView(BusinessMessage m,boolean read){String name=m.getTargetBusinessId()==null?null:business(m.getTargetBusinessId()).getName();return new CommunicationResponses.BusinessMessageView(m.getId(),m.getTargetBusinessId(),name,m.getMessageType(),m.getSubject(),m.getBody(),read,m.getCreatedAt());}
 private void addReply(SupportTicket t,Long sender,CommunicationSenderType type,String body){SupportTicketMessage m=new SupportTicketMessage();m.setTicketId(t.getId());m.setSenderUserId(sender);m.setSenderType(type);m.setBody(text(body,4000,"Message"));ticketMessages.save(m);}
 private void notifyAdmins(String title,String body,Long ticketId){for(User a:users.findByRoleAndStatus(UserRole.ADMIN,UserStatus.ACTIVE))notifications.notify(a.getId(),NotificationType.SUPPORT_TICKET,title,body,"SUPPORT_TICKET",ticketId);}
 private Business ownerBusiness(Long owner){return businesses.findByOwnerUserId(owner).orElseThrow(()->new ResourceNotFoundException("No business found for this owner"));} private SupportTicket ownTicket(Long owner,Long id){Business b=ownerBusiness(owner);return tickets.findByIdAndBusinessId(id,b.getId()).orElseThrow(()->new ResourceNotFoundException("Ticket not found"));} private SupportTicket ticket(Long id){return tickets.findById(id).orElseThrow(()->new ResourceNotFoundException("Ticket not found"));} private Business business(Long id){return businesses.findById(id).orElseThrow(()->new ResourceNotFoundException("Business not found"));}
 private void ensureOpen(SupportTicket t){if(t.getStatus()==TicketStatus.CLOSED)throw new InvalidRequestException("Closed tickets cannot receive replies");} private String text(String v,int max,String field){String x=v==null?"":v.strip().replaceAll("\\s+"," ");if(x.isEmpty()||x.length()>max)throw new InvalidRequestException(field+" is required and must be at most "+max+" characters");return x;} private PageRequest page(int p,int l){if(p<0||p>100||l<1||l>50)throw new InvalidRequestException("Invalid pagination");return PageRequest.of(p,l);}
}
