package com.foody.wallet.service;
import com.foody.businesses.entity.Business; import com.foody.businesses.repository.BusinessRepository;
import com.foody.common.exception.*; import com.foody.users.entity.User; import com.foody.users.entity.UserRole; import com.foody.users.repository.UserRepository;
import com.foody.wallet.dto.*; import com.foody.wallet.entity.*; import com.foody.wallet.repository.*;
import com.foody.products.entity.Product; import com.foody.products.repository.ProductRepository;
import java.math.BigDecimal; import java.time.Instant; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors; import org.springframework.data.domain.Sort; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service class WalletServiceImpl implements WalletService {
 private final WalletRepository wallets; private final WalletTransactionRepository txs; private final OwnerDebitRequestRepository requests; private final BusinessRepository businesses; private final UserRepository users; private final ProductRepository products; private final WalletPurchaseItemRepository purchaseItems;
 WalletServiceImpl(WalletRepository w,WalletTransactionRepository t,OwnerDebitRequestRepository r,BusinessRepository b,UserRepository u,ProductRepository p,WalletPurchaseItemRepository pi){wallets=w;txs=t;requests=r;businesses=b;users=u;products=p;purchaseItems=pi;}
 @Transactional(readOnly=true) public List<WalletResponse> customerWallets(Long id){User customer=walletCustomer(id);return wallets.findByCustomerUserIdOrderByCreatedAtDesc(id).stream().filter(w->canUseAt(customer,w.getBusinessId())).map(WalletResponse::from).toList();}
 @Transactional(readOnly=true) public List<WalletTransactionResponse> customerTransactions(Long cid,Long wid){User customer=walletCustomer(cid);Wallet w=wallets.findById(wid).filter(x->x.getCustomerUserId().equals(cid)).orElseThrow(()->new ResourceNotFoundException("Wallet not found"));ensureNotOwnBusiness(customer,w.getBusinessId());return history(w.getId());}
 @Transactional(readOnly=true) public List<DebitRequestResponse> pendingRequests(Long id){User customer=walletCustomer(id);return requests.findByCustomerUserIdAndStatusOrderByCreatedAtDesc(id,DebitRequestStatus.PENDING).stream().filter(r->canUseAt(customer,r.getBusinessId())).map(this::debitResponse).toList();}
 @Transactional public DebitRequestResponse approve(Long cid,Long rid){User customer=walletCustomer(cid);OwnerDebitRequest r=lockedOwnRequest(cid,rid);ensureNotOwnBusiness(customer,r.getBusinessId()); ensurePending(r); Wallet w=wallets.findByIdForUpdate(r.getWalletId()).orElseThrow(()->new ResourceNotFoundException("Wallet not found")); if(w.getBalance().compareTo(r.getAmount())<0)throw new InsufficientBalanceException("Insufficient wallet balance"); w.setBalance(w.getBalance().subtract(r.getAmount())); wallets.save(w); r.setStatus(DebitRequestStatus.APPROVED);r.setResolvedAt(Instant.now());requests.save(r); ledger(w,r.getAmount(),WalletTransactionType.OWNER_DEBIT,r.getRequestedByOwnerUserId(),WalletActorType.OWNER,r.getId());return DebitRequestResponse.from(r);}
 @Transactional public DebitRequestResponse reject(Long cid,Long rid){User customer=walletCustomer(cid);OwnerDebitRequest r=lockedOwnRequest(cid,rid);ensureNotOwnBusiness(customer,r.getBusinessId());ensurePending(r);r.setStatus(DebitRequestStatus.REJECTED);r.setResolvedAt(Instant.now());return DebitRequestResponse.from(requests.save(r));}
 @Transactional(readOnly=true) public List<OwnerWalletResponse> ownerWallets(Long oid){return wallets.findByBusinessIdOrderByCreatedAtDesc(ownerBusiness(oid).getId()).stream().map(w->OwnerWalletResponse.from(w,customer(w.getCustomerUserId()))).toList();}
 @Transactional(readOnly=true) public CustomerLookupResponse ownerLookupCustomer(Long oid,String publicId){Business business=ownerBusiness(oid);User customer=customer(publicId);ensureNotOwnBusiness(customer,business.getId());return CustomerLookupResponse.from(customer);}
 @Transactional public OwnerWalletResponse ownerCreditByPublicId(Long oid,String publicId,BigDecimal amount){Business b=ownerBusiness(oid);User customer=customer(publicId);Wallet w=getOrCreate(customer.getId(),b.getId());apply(w,amount,true,WalletTransactionType.OWNER_CREDIT,oid,WalletActorType.OWNER,null);return OwnerWalletResponse.from(w,customer);}
 @Transactional public DebitRequestResponse ownerRequestDebitByPublicId(Long oid,String publicId,BigDecimal amount){return ownerRequestDebit(oid,customer(publicId).getId(),amount);}
 @Transactional public DebitRequestResponse ownerCreatePurchase(Long oid,String publicId,CreatePurchaseRequest request){
  Business b=ownerBusiness(oid); User customer=customer(publicId); ensureNotOwnBusiness(customer,b.getId());
  Map<Long,Integer> quantities=new LinkedHashMap<>();
  for(PurchaseItemRequest item:request.items()) quantities.merge(item.productId(),item.quantity(),Math::addExact);
  Map<Long,Product> found=products.findAvailableForBusiness(b.getId(),new ArrayList<>(quantities.keySet())).stream().collect(Collectors.toMap(Product::getId,Function.identity()));
  if(found.size()!=quantities.size()) throw new InvalidRequestException("Every item must be an available product of this business");
  BigDecimal total=BigDecimal.ZERO; List<WalletPurchaseItem> snapshots=new ArrayList<>();
  for(var entry:quantities.entrySet()){Product p=found.get(entry.getKey());BigDecimal line=p.getPrice().multiply(BigDecimal.valueOf(entry.getValue()));total=total.add(line);WalletPurchaseItem i=new WalletPurchaseItem();i.setProductId(p.getId());i.setProductNameSnapshot(p.getName());i.setUnitPriceSnapshot(p.getPrice());i.setQuantity(entry.getValue());i.setLineTotal(line);snapshots.add(i);}
  requirePositive(total); Wallet w=getOrCreate(customer.getId(),b.getId()); OwnerDebitRequest debit=new OwnerDebitRequest(); debit.setWalletId(w.getId());debit.setCustomerUserId(customer.getId());debit.setBusinessId(b.getId());debit.setRequestedByOwnerUserId(oid);debit.setAmount(total);debit=requests.saveAndFlush(debit);
  for(WalletPurchaseItem item:snapshots)item.setDebitRequestId(debit.getId()); purchaseItems.saveAll(snapshots); return DebitRequestResponse.from(debit,b.getName(),snapshots);
 }
 @Transactional(readOnly=true) public List<PurchaseHistoryResponse> customerPurchaseHistory(Long cid){User customer=walletCustomer(cid);return requests.findByCustomerUserIdAndStatusOrderByResolvedAtDesc(cid,DebitRequestStatus.APPROVED).stream().filter(r->canUseAt(customer,r.getBusinessId())&&!purchaseItems.findByDebitRequestIdOrderById(r.getId()).isEmpty()).map(this::purchaseHistory).toList();}
 @Transactional(readOnly=true) public List<PurchaseHistoryResponse> ownerSalesHistory(Long oid){Business b=ownerBusiness(oid);return requests.findByBusinessIdAndStatusOrderByResolvedAtDesc(b.getId(),DebitRequestStatus.APPROVED).stream().filter(r->!purchaseItems.findByDebitRequestIdOrderById(r.getId()).isEmpty()).map(this::purchaseHistory).toList();}
 @Transactional public WalletResponse ownerCredit(Long oid,Long cid,BigDecimal amount){Business b=ownerBusiness(oid);Wallet w=getOrCreate(cid,b.getId());apply(w,amount,true,WalletTransactionType.OWNER_CREDIT,oid,WalletActorType.OWNER,null);return WalletResponse.from(w);}
 @Transactional public DebitRequestResponse ownerRequestDebit(Long oid,Long cid,BigDecimal amount){requirePositive(amount);Business b=ownerBusiness(oid);Wallet w=getOrCreate(cid,b.getId());OwnerDebitRequest r=new OwnerDebitRequest();r.setWalletId(w.getId());r.setCustomerUserId(cid);r.setBusinessId(b.getId());r.setRequestedByOwnerUserId(oid);r.setAmount(amount);return DebitRequestResponse.from(requests.save(r));}
 @Transactional public WalletResponse adminCredit(Long aid,Long cid,Long bid,BigDecimal amount){Wallet w=getOrCreate(cid,checkedBusiness(bid).getId());apply(w,amount,true,WalletTransactionType.ADMIN_CREDIT,aid,WalletActorType.ADMIN,null);return WalletResponse.from(w);}
 @Transactional public WalletResponse adminDebit(Long aid,Long cid,Long bid,BigDecimal amount){Wallet w=getOrCreate(cid,checkedBusiness(bid).getId());apply(w,amount,false,WalletTransactionType.ADMIN_DEBIT,aid,WalletActorType.ADMIN,null);return WalletResponse.from(w);}
 @Transactional(readOnly=true) public List<WalletResponse> adminWallets(){return wallets.findAll(Sort.by(Sort.Direction.DESC,"createdAt")).stream().map(WalletResponse::from).toList();}
 @Transactional(readOnly=true) public List<WalletTransactionResponse> adminTransactions(Long wid){if(!wallets.existsById(wid))throw new ResourceNotFoundException("Wallet not found");return history(wid);}
 private List<WalletTransactionResponse> history(Long id){return txs.findByWalletIdOrderByCreatedAtDesc(id).stream().map(WalletTransactionResponse::from).toList();}
 private DebitRequestResponse debitResponse(OwnerDebitRequest r){return DebitRequestResponse.from(r,checkedBusiness(r.getBusinessId()).getName(),purchaseItems.findByDebitRequestIdOrderById(r.getId()));}
 private PurchaseHistoryResponse purchaseHistory(OwnerDebitRequest r){Business b=checkedBusiness(r.getBusinessId());User c=customer(r.getCustomerUserId());return new PurchaseHistoryResponse(r.getId(),b.getId(),b.getName(),c.getId(),c.getFullName(),r.getResolvedAt(),r.getAmount(),purchaseItems.findByDebitRequestIdOrderById(r.getId()).stream().map(PurchaseItemResponse::from).toList());}
 private OwnerDebitRequest lockedOwnRequest(Long cid,Long rid){return requests.findByIdForUpdate(rid).filter(r->r.getCustomerUserId().equals(cid)).orElseThrow(()->new ResourceNotFoundException("Debit request not found"));}
 private void ensurePending(OwnerDebitRequest r){if(r.getStatus()!=DebitRequestStatus.PENDING)throw new InvalidStateTransitionException("Debit request is already resolved");}
 private Business ownerBusiness(Long oid){return businesses.findByOwnerUserId(oid).orElseThrow(()->new ResourceNotFoundException("No business found for this owner"));}
 private Business checkedBusiness(Long bid){return businesses.findById(bid).orElseThrow(()->new ResourceNotFoundException("Business not found: "+bid));}
 private User customer(String publicId){if(publicId==null||!publicId.matches("F-[0-9A-F]{16}"))throw new ResourceNotFoundException("Customer not found");return users.findByPublicId(publicId).filter(this::isWalletCustomer).orElseThrow(()->new ResourceNotFoundException("Customer not found"));}
 private User customer(Long id){return walletCustomer(id);}
 private User walletCustomer(Long id){return users.findById(id).filter(this::isWalletCustomer).orElseThrow(()->new ResourceNotFoundException("Customer not found: "+id));}
 private boolean isWalletCustomer(User user){return user.getRole()==UserRole.CUSTOMER||user.getRole()==UserRole.BUSINESS_OWNER;}
 private Wallet getOrCreate(Long cid,Long bid){User customer=walletCustomer(cid);ensureNotOwnBusiness(customer,bid);return wallets.findByCustomerUserIdAndBusinessId(cid,bid).orElseGet(()->{Wallet w=new Wallet();w.setCustomerUserId(cid);w.setBusinessId(bid);return wallets.saveAndFlush(w);});}
 private boolean canUseAt(User customer,Long businessId){return customer.getRole()!=UserRole.BUSINESS_OWNER||businesses.findByOwnerUserId(customer.getId()).map(b->!b.getId().equals(businessId)).orElse(true);}
 private void ensureNotOwnBusiness(User customer,Long businessId){if(!canUseAt(customer,businessId))throw new AccessDeniedException("Business owners cannot use a personal wallet at their own business");}
 private void apply(Wallet w,BigDecimal a,boolean credit,WalletTransactionType type,Long actor,WalletActorType actorType,Long req){requirePositive(a);Wallet locked=wallets.findByIdForUpdate(w.getId()).orElseThrow();if(!credit&&locked.getBalance().compareTo(a)<0)throw new InsufficientBalanceException("Insufficient wallet balance");locked.setBalance(credit?locked.getBalance().add(a):locked.getBalance().subtract(a));wallets.save(locked);ledger(locked,a,type,actor,actorType,req);w.setBalance(locked.getBalance());}
 private void requirePositive(BigDecimal amount){if(amount==null||amount.signum()<=0||amount.scale()>2)throw new InvalidRequestException("Amount must be positive with at most two decimal places");}
 private void ledger(Wallet w,BigDecimal a,WalletTransactionType type,Long actor,WalletActorType at,Long req){WalletTransaction t=new WalletTransaction();t.setWalletId(w.getId());t.setAmount(a);t.setType(type);t.setActorUserId(actor);t.setActorType(at);t.setBalanceAfter(w.getBalance());t.setDebitRequestId(req);txs.save(t);}
}
