package com.foody.communications;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.foody.AbstractContainerBaseTest; import com.foody.auth.security.JwtService; import com.foody.businesses.entity.*; import com.foody.businesses.repository.BusinessRepository; import com.foody.common.exception.*; import com.foody.communications.dto.*; import com.foody.communications.entity.*; import com.foody.communications.service.CommunicationService; import com.foody.users.entity.*; import com.foody.users.repository.UserRepository; import java.util.UUID; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc;
@AutoConfigureMockMvc class CommunicationIntegrationTest extends AbstractContainerBaseTest {
 @Autowired CommunicationService service; @Autowired UserRepository users; @Autowired BusinessRepository businesses; @Autowired MockMvc mvc; @Autowired JwtService jwt;
 User owner1,owner2,admin,customer; Business business1,business2;
 @BeforeEach void setup(){owner1=user(UserRole.BUSINESS_OWNER);owner2=user(UserRole.BUSINESS_OWNER);admin=user(UserRole.ADMIN);customer=user(UserRole.CUSTOMER);business1=business(owner1,"Support Cafe");business2=business(owner2,"Other Cafe");}
 @Test void ownerCreatesAndReadsOnlyOwnTicketWhileAdminCanReplyAndClose(){var created=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("  Need help  ","Please help"));assertThat(created.ticket().businessId()).isEqualTo(business1.getId());assertThat(created.ticket().ownerDisplayName()).isEqualTo(owner1.getFullName());assertThat(service.ownerTickets(owner1.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(created.ticket().id());assertThat(service.ownerTickets(owner2.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).doesNotContain(created.ticket().id());assertThatThrownBy(()->service.ownerTicket(owner2.getId(),created.ticket().id())).isInstanceOf(ResourceNotFoundException.class);assertThat(service.adminTickets(TicketStatus.OPEN,0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(created.ticket().id());var answered=service.adminReply(admin.getId(),created.ticket().id(),new CommunicationRequests.Reply("Admin answer"));assertThat(answered.ticket().status()).isEqualTo(TicketStatus.ANSWERED);assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isEqualTo(1);assertThat(service.ownerTicket(owner1.getId(),created.ticket().id()).messages()).extracting(CommunicationResponses.TicketMessage::body).contains("Admin answer");assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();assertThat(service.closeTicket(admin.getId(),created.ticket().id()).ticket().status()).isEqualTo(TicketStatus.CLOSED);assertThatThrownBy(()->service.ownerReply(owner1.getId(),created.ticket().id(),new CommunicationRequests.Reply("late"))).isInstanceOf(InvalidRequestException.class);}
 @Test void adminViewingAnAnsweredTicketDoesNotMakeItUnreadAgainForItsOwner(){var created=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("Need help","Please help"));service.adminReply(admin.getId(),created.ticket().id(),new CommunicationRequests.Reply("Admin answer"));service.ownerTicket(owner1.getId(),created.ticket().id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();service.adminTicket(admin.getId(),created.ticket().id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();}
 @Test void directMessageIsIsolatedAndTransitionsUnreadToRead(){var sent=service.sendDirect(admin.getId(),new CommunicationRequests.DirectMessage(business1.getId(),"Featured","Contact us"));assertThat(sent.targetBusinessId()).isEqualTo(business1.getId());assertThat(service.ownerMessages(owner1.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());assertThat(service.ownerMessages(owner2.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).doesNotContain(sent.id());assertThatThrownBy(()->service.ownerMessage(owner2.getId(),sent.id())).isInstanceOf(ResourceNotFoundException.class);assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isEqualTo(1);assertThat(service.ownerMessage(owner1.getId(),sent.id()).read()).isTrue();assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();}
 @Test void oneBroadcastIsVisibleAndReadIndependentlyByEachBusiness(){var sent=service.sendBroadcast(admin.getId(),new CommunicationRequests.Broadcast("Announcement","For every business"));assertThat(sent.type()).isEqualTo(BusinessMessageType.BROADCAST);assertThat(service.ownerMessages(owner1.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());assertThat(service.ownerMessages(owner2.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());service.ownerMessage(owner1.getId(),sent.id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();assertThat(service.ownerUnread(owner2.getId()).unreadCount()).isEqualTo(1);}
 @Test void roleGuardsBlockCustomersAndOwnerAdminSpoofing() throws Exception {String body="{\"subject\":\"hello\",\"message\":\"body\"}";mvc.perform(get("/api/business/communications/tickets").header("Authorization",bearer(customer))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/communications/messages/broadcast").header("Authorization",bearer(owner1)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());mvc.perform(post("/api/business/communications/tickets").header("Authorization",bearer(owner1)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());}
 @Test void blankAndOversizeContentAndPaginationAreRejected(){assertThatThrownBy(()->service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket(" ","body"))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->service.ownerTickets(owner1.getId(),0,51)).isInstanceOf(InvalidRequestException.class);}
 private User user(UserRole role){User u=new User();u.setEmail(UUID.randomUUID()+"@communications.test");u.setFullName(role+" sender");u.setPasswordHash("unused");u.setRole(role);u.setStatus(UserStatus.ACTIVE);return users.saveAndFlush(u);} private Business business(User owner,String name){Business b=new Business();b.setOwnerUserId(owner.getId());b.setName(name+UUID.randomUUID());b.setBusinessType("CAFE");b.setStatus(BusinessStatus.APPROVED);return businesses.saveAndFlush(b);} private String bearer(User u){return "Bearer "+jwt.generateAccessToken(u);}
}
