package com.foody.communications;
import static org.assertj.core.api.Assertions.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import com.foody.AbstractContainerBaseTest; import com.foody.auth.security.JwtService; import com.foody.businesses.entity.*; import com.foody.businesses.repository.BusinessRepository; import com.foody.common.exception.*; import com.foody.communications.dto.*; import com.foody.communications.entity.*; import com.foody.communications.service.CommunicationService; import com.foody.users.entity.*; import com.foody.users.repository.UserRepository; import java.util.UUID; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc;
@AutoConfigureMockMvc class CommunicationIntegrationTest extends AbstractContainerBaseTest {
 @Autowired CommunicationService service; @Autowired UserRepository users; @Autowired BusinessRepository businesses; @Autowired MockMvc mvc; @Autowired JwtService jwt;
 User owner1,owner2,admin,customer,customer2; Business business1,business2;
 @BeforeEach void setup(){owner1=user(UserRole.BUSINESS_OWNER);owner2=user(UserRole.BUSINESS_OWNER);admin=user(UserRole.ADMIN);customer=user(UserRole.CUSTOMER);customer2=user(UserRole.CUSTOMER);business1=business(owner1,"Support Cafe");business2=business(owner2,"Other Cafe");}
 @Test void ownerCreatesAndReadsOnlyOwnTicketWhileAdminCanReplyAndClose(){var created=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("  Need help  ","Please help"));assertThat(created.ticket().businessId()).isEqualTo(business1.getId());assertThat(created.ticket().requesterType()).isEqualTo(TicketRequesterType.BUSINESS_OWNER);assertThat(created.ticket().requesterDisplayName()).isEqualTo(owner1.getFullName());assertThat(service.ownerTickets(owner1.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(created.ticket().id());assertThat(service.ownerTickets(owner2.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).doesNotContain(created.ticket().id());assertThatThrownBy(()->service.ownerTicket(owner2.getId(),created.ticket().id())).isInstanceOf(ResourceNotFoundException.class);assertThat(service.adminTickets(TicketStatus.OPEN,null,0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(created.ticket().id());var answered=service.adminReply(admin.getId(),created.ticket().id(),new CommunicationRequests.Reply("Admin answer"));assertThat(answered.ticket().status()).isEqualTo(TicketStatus.ANSWERED);assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isEqualTo(1);assertThat(service.ownerTicket(owner1.getId(),created.ticket().id()).messages()).extracting(CommunicationResponses.TicketMessage::body).contains("Admin answer");assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();assertThat(service.closeTicket(admin.getId(),created.ticket().id()).ticket().status()).isEqualTo(TicketStatus.CLOSED);assertThatThrownBy(()->service.ownerReply(owner1.getId(),created.ticket().id(),new CommunicationRequests.Reply("late"))).isInstanceOf(InvalidRequestException.class);}
 @Test void adminViewingAnAnsweredTicketDoesNotMakeItUnreadAgainForItsOwner(){var created=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("Need help","Please help"));service.adminReply(admin.getId(),created.ticket().id(),new CommunicationRequests.Reply("Admin answer"));service.ownerTicket(owner1.getId(),created.ticket().id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();service.adminTicket(admin.getId(),created.ticket().id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();}
 @Test void directMessageIsIsolatedAndTransitionsUnreadToRead(){var sent=service.sendDirect(admin.getId(),new CommunicationRequests.DirectMessage(business1.getId(),"Featured","Contact us"));assertThat(sent.targetBusinessId()).isEqualTo(business1.getId());assertThat(service.ownerMessages(owner1.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());assertThat(service.ownerMessages(owner2.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).doesNotContain(sent.id());assertThatThrownBy(()->service.ownerMessage(owner2.getId(),sent.id())).isInstanceOf(ResourceNotFoundException.class);assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isEqualTo(1);assertThat(service.ownerMessage(owner1.getId(),sent.id()).read()).isTrue();assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();}
 @Test void oneBroadcastIsVisibleAndReadIndependentlyByEachBusiness(){var sent=service.sendBroadcast(admin.getId(),new CommunicationRequests.Broadcast("Announcement","For every business"));assertThat(sent.type()).isEqualTo(BusinessMessageType.BROADCAST);assertThat(service.ownerMessages(owner1.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());assertThat(service.ownerMessages(owner2.getId(),0,20).items()).extracting(CommunicationResponses.BusinessMessageView::id).contains(sent.id());service.ownerMessage(owner1.getId(),sent.id());assertThat(service.ownerUnread(owner1.getId()).unreadCount()).isZero();assertThat(service.ownerUnread(owner2.getId()).unreadCount()).isEqualTo(1);}
 @Test void roleGuardsBlockCustomersAndOwnerAdminSpoofing() throws Exception {String body="{\"subject\":\"hello\",\"message\":\"body\"}";mvc.perform(get("/api/business/communications/tickets").header("Authorization",bearer(customer))).andExpect(status().isForbidden());mvc.perform(post("/api/admin/communications/messages/broadcast").header("Authorization",bearer(owner1)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isForbidden());mvc.perform(post("/api/business/communications/tickets").header("Authorization",bearer(owner1)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());}
 @Test void blankAndOversizeContentAndPaginationAreRejected(){assertThatThrownBy(()->service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket(" ","body"))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->service.ownerTickets(owner1.getId(),0,51)).isInstanceOf(InvalidRequestException.class);}

 // --- Customer support tickets ---

 @Test void customerCreatesTicketWithoutABusinessAndItRequiresNoBusinessContext(){var created=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("  Payment issue  ","My wallet balance looks wrong"));assertThat(created.ticket().businessId()).isNull();assertThat(created.ticket().businessName()).isNull();assertThat(created.ticket().requesterType()).isEqualTo(TicketRequesterType.CUSTOMER);assertThat(created.ticket().requesterDisplayName()).isEqualTo(customer.getFullName());assertThat(created.ticket().requesterPublicId()).isEqualTo(customer.getPublicId());assertThat(created.messages()).extracting(CommunicationResponses.TicketMessage::senderType).containsExactly(CommunicationSenderType.CUSTOMER);}
 @Test void customerListsOnlyOwnTicketsAndCannotReadAnotherCustomersTicket(){var mine=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("Subject A","Body A"));var theirs=service.createCustomerTicket(customer2.getId(),new CommunicationRequests.CreateTicket("Subject B","Body B"));assertThat(service.customerTickets(customer.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(mine.ticket().id()).doesNotContain(theirs.ticket().id());assertThatThrownBy(()->service.customerTicket(customer.getId(),theirs.ticket().id())).isInstanceOf(ResourceNotFoundException.class);}
 @Test void customerCannotReadABusinessOwnerTicketAndOwnerCannotReadACustomerTicket(){var ownerTicket=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("Owner subject","Owner body"));var customerTicket=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("Customer subject","Customer body"));assertThatThrownBy(()->service.customerTicket(customer.getId(),ownerTicket.ticket().id())).isInstanceOf(ResourceNotFoundException.class);assertThatThrownBy(()->service.ownerTicket(owner1.getId(),customerTicket.ticket().id())).isInstanceOf(ResourceNotFoundException.class);assertThat(service.ownerTickets(owner1.getId(),0,20).items()).extracting(CommunicationResponses.TicketSummary::id).doesNotContain(customerTicket.ticket().id());}
 @Test void customerRepliesAndSeesAdminReplyAndUnreadClearsOnOpen(){var created=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("Need help","Please help"));var answered=service.adminReply(admin.getId(),created.ticket().id(),new CommunicationRequests.Reply("Admin answer for customer"));assertThat(answered.ticket().status()).isEqualTo(TicketStatus.ANSWERED);assertThat(service.customerUnread(customer.getId()).unreadCount()).isEqualTo(1);var opened=service.customerTicket(customer.getId(),created.ticket().id());assertThat(opened.messages()).extracting(CommunicationResponses.TicketMessage::body).contains("Admin answer for customer");assertThat(service.customerUnread(customer.getId()).unreadCount()).isZero();var replied=service.customerReply(customer.getId(),created.ticket().id(),new CommunicationRequests.Reply("Thanks, follow-up question"));assertThat(replied.ticket().status()).isEqualTo(TicketStatus.OPEN);assertThat(service.adminTickets(TicketStatus.OPEN,TicketRequesterType.CUSTOMER,0,20).items()).extracting(CommunicationResponses.TicketSummary::id).contains(created.ticket().id());}
 @Test void adminSeesBothTicketSourcesAndCanReplyAndCloseCustomerTickets(){var ownerTicket=service.createTicket(owner1.getId(),new CommunicationRequests.CreateTicket("Owner subject","Owner body"));var customerTicket=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("Customer subject","Customer body"));var all=service.adminTickets(null,null,0,50).items();assertThat(all).extracting(CommunicationResponses.TicketSummary::id).contains(ownerTicket.ticket().id(),customerTicket.ticket().id());assertThat(service.adminTickets(null,TicketRequesterType.CUSTOMER,0,50).items()).extracting(CommunicationResponses.TicketSummary::id).contains(customerTicket.ticket().id()).doesNotContain(ownerTicket.ticket().id());var closed=service.closeTicket(admin.getId(),customerTicket.ticket().id());assertThat(closed.ticket().status()).isEqualTo(TicketStatus.CLOSED);assertThatThrownBy(()->service.customerReply(customer.getId(),customerTicket.ticket().id(),new CommunicationRequests.Reply("late"))).isInstanceOf(InvalidRequestException.class);}
 @Test void oneCustomersUnreadStateNeverAffectsAnothersAndAdminEndpointsAreCustomerBlocked() throws Exception {var t1=service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket("Subject A","Body A"));var t2=service.createCustomerTicket(customer2.getId(),new CommunicationRequests.CreateTicket("Subject B","Body B"));service.adminReply(admin.getId(),t1.ticket().id(),new CommunicationRequests.Reply("Answer for customer 1"));assertThat(service.customerUnread(customer.getId()).unreadCount()).isEqualTo(1);assertThat(service.customerUnread(customer2.getId()).unreadCount()).isZero();mvc.perform(get("/api/admin/communications/tickets").header("Authorization",bearer(customer))).andExpect(status().isForbidden());mvc.perform(patch("/api/admin/communications/tickets/"+t2.ticket().id()+"/close").header("Authorization",bearer(customer))).andExpect(status().isForbidden());}
 @Test void customerCannotSpoofSenderIdentityAndCustomerTicketRequestsGoThroughAuthenticatedEndpoint() throws Exception {String body="{\"subject\":\"Payment\",\"message\":\"My order failed\"}";mvc.perform(post("/api/customer/communications/tickets").header("Authorization",bearer(customer)).contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isCreated());mvc.perform(get("/api/customer/communications/tickets").header("Authorization",bearer(owner1))).andExpect(status().isForbidden());mvc.perform(get("/api/customer/communications/tickets").header("Authorization",bearer(admin))).andExpect(status().isForbidden());var created=service.customerTickets(customer.getId(),0,20).items().get(0);assertThat(created.requesterDisplayName()).isEqualTo(customer.getFullName());}
 @Test void customerBlankAndOversizeContentIsRejected(){assertThatThrownBy(()->service.createCustomerTicket(customer.getId(),new CommunicationRequests.CreateTicket(" ","body"))).isInstanceOf(InvalidRequestException.class);assertThatThrownBy(()->service.customerTickets(customer.getId(),0,51)).isInstanceOf(InvalidRequestException.class);}

 private User user(UserRole role){User u=new User();u.setEmail(UUID.randomUUID()+"@communications.test");u.setFullName(role+" sender");u.setPasswordHash("unused");u.setRole(role);u.setStatus(UserStatus.ACTIVE);return users.saveAndFlush(u);} private Business business(User owner,String name){Business b=new Business();b.setOwnerUserId(owner.getId());b.setName(name+UUID.randomUUID());b.setBusinessType("CAFE");b.setStatus(BusinessStatus.APPROVED);return businesses.saveAndFlush(b);} private String bearer(User u){return "Bearer "+jwt.generateAccessToken(u);}
}
