import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const section=await readFile(new URL("../src/features/business-detail/ReviewsSection.tsx",import.meta.url),"utf8");
const editor=await readFile(new URL("../src/features/business-detail/ReviewEditor.tsx",import.meta.url),"utf8");
const products=await readFile(new URL("../src/features/business-detail/ProductReviews.tsx",import.meta.url),"utf8");
const productApi=await readFile(new URL("../src/features/business-detail/productReviewApi.ts",import.meta.url),"utf8");
const menu=await readFile(new URL("../src/features/business-detail/MenuSection.tsx",import.meta.url),"utf8");
const owner=await readFile(new URL("../src/features/owner/OwnerReviewsPage.tsx",import.meta.url),"utf8");
const ownerNav=await readFile(new URL("../src/features/owner/ownerNav.tsx",import.meta.url),"utf8");
const app=await readFile(new URL("../src/App.tsx",import.meta.url),"utf8");
test("existing business review is a compact card until edit is clicked",()=>{assert.match(section,/ReviewCard review=\{mine\.data\} mine/);assert.match(section,/onEdit=\{\(\)=>setEditing\(true\)\}/);assert.match(section,/canWrite&&editing&&<ReviewEditor/);assert.doesNotMatch(section,/mine\.data&&<ReviewEditor/)});
test("shared editor supports save and cancel accessibly",()=>{assert.match(editor,/aria-label="ویرایش نظر"/);assert.match(editor,/type="radio"/);assert.match(editor,/onSave\(rating,comment\.trim\(\)\|\|null\)/);assert.match(editor,/onClick=\{onCancel\}/)});
test("business save refreshes public and own review",()=>{assert.match(section,/reviewApi\.update\(businessId/);assert.match(section,/reviewApi\.create\(businessId/);assert.match(section,/invalidateQueries\(\{queryKey:reviewsKey\(businessId\)\}\)/);assert.match(section,/invalidateQueries\(\{queryKey:mineKey\(businessId\)\}\)/)});
test("product reviews are compact and use complete CRUD API",()=>{assert.match(menu,/ProductReviews productId=\{product\.id\} canReview=\{canOrder\}/);assert.match(products,/مشاهده نظرات/);assert.match(products,/canReview&&editing&&<ReviewEditor/);for(const method of ["list","mine","create","update","remove"])assert.match(productApi,new RegExp(`${method}:`))});
test("owner dashboard has separate business and item review sections and replaces messages",()=>{assert.match(owner,/نظرات کسب‌وکار/);assert.match(owner,/نظرات محصولات/);assert.match(owner,/productName/);assert.match(ownerNav,/to: "\/business\/reviews", label: "نظرات"/);assert.doesNotMatch(ownerNav,/\/business\/messages/);assert.match(app,/path="\/business\/reviews" element=\{<OwnerReviewsPage/)});
test("admin moderation exists without customer editor eligibility",()=>{assert.match(products,/user\?\.role==="ADMIN"/);assert.match(productApi,/adminRemove/);assert.doesNotMatch(section,/user\?\.role==="ADMIN".*canWrite/)});
