import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const section=await readFile(new URL("../src/features/business-detail/ReviewsSection.tsx",import.meta.url),"utf8");
const editor=await readFile(new URL("../src/features/business-detail/ReviewEditor.tsx",import.meta.url),"utf8");
const products=await readFile(new URL("../src/features/business-detail/ProductReviews.tsx",import.meta.url),"utf8");
const productApi=await readFile(new URL("../src/features/business-detail/productReviewApi.ts",import.meta.url),"utf8");
const menu=await readFile(new URL("../src/features/business-detail/MenuSection.tsx",import.meta.url),"utf8");
const owner=await readFile(new URL("../src/features/owner/OwnerReviewsPage.tsx",import.meta.url),"utf8");
const ownerNav=await readFile(new URL("../src/features/owner/ownerNav.tsx",import.meta.url),"utf8");
const app=await readFile(new URL("../src/App.tsx",import.meta.url),"utf8");
const admin=await readFile(new URL("../src/features/admin/AdminReviewsPage.tsx",import.meta.url),"utf8");
const adminApi=await readFile(new URL("../src/features/admin/adminApi.ts",import.meta.url),"utf8");
const css=await readFile(new URL("../src/features/business-detail/business-detail.css",import.meta.url),"utf8");
test("existing business review is a compact card until edit is clicked",()=>{assert.match(section,/ReviewCard review=\{mine\.data\} mine/);assert.match(section,/onEdit=\{\(\)=>setEditing\(true\)\}/);assert.match(section,/canWrite&&editing&&<ReviewEditor/);assert.doesNotMatch(section,/mine\.data&&<ReviewEditor/)});
test("shared editor supports save and cancel accessibly",()=>{assert.match(editor,/aria-label="ویرایش نظر"/);assert.match(editor,/type="radio"/);assert.match(editor,/onSave\(rating,comment\.trim\(\)\|\|null\)/);assert.match(editor,/onClick=\{onCancel\}/)});
test("rating input highlights the selected prefix and explains missing rating",()=>{assert.match(editor,/visibleRating>=v/);assert.match(editor,/hoveredRating\|\|rating/);assert.match(editor,/لطفاً میزان رضایت خود را انتخاب کنید/);assert.doesNotMatch(editor,/disabled=\{!rating\}/)});
test("business save refreshes public and own review",()=>{assert.match(section,/reviewApi\.update\(businessId/);assert.match(section,/reviewApi\.create\(businessId/);assert.match(section,/invalidateQueries\(\{queryKey:reviewsKey\(businessId\)\}\)/);assert.match(section,/invalidateQueries\(\{queryKey:mineKey\(businessId\)\}\)/)});
test("public business reviews refresh after an external moderation decision without duplicate rendering",()=>{assert.match(section,/refetchOnMount:"always"/);assert.match(section,/refetchOnWindowFocus:true/);assert.match(section,/reviews\.data\?\.reviews\.filter\(review=>review\.id!==mine\.data\?\.id\)/);assert.match(section,/<ReviewCard review=\{mine\.data\} mine/);assert.match(section,/publicReviews\.slice\(0,visibleCount\)\.map\(review=><ReviewCard key=\{review\.id\} review=\{review\}\/>\)/)});
test("product reviews are compact and use complete CRUD API",()=>{assert.match(menu,/ProductReviews productId=\{product\.id\} canReview=\{canReview\}/);assert.match(products,/مشاهده نظرات/);assert.match(products,/canReview&&editing&&<ReviewEditor/);for(const method of ["list","mine","create","update","remove"])assert.match(productApi,new RegExp(`${method}:`))});
test("owner dashboard has separate business and item review sections and replaces messages",()=>{assert.match(owner,/نظرات کسب‌وکار/);assert.match(owner,/نظرات محصولات/);assert.match(owner,/productName/);assert.match(ownerNav,/to: "\/business\/reviews", label: "نظرات"/);assert.doesNotMatch(ownerNav,/\/business\/messages/);assert.match(app,/path="\/business\/reviews" element=\{<OwnerReviewsPage/)});
test("customer receives truthful pending moderation feedback",()=>{assert.match(section,/پس از تأیید مدیر نمایش داده می‌شود/);assert.match(products,/پس از تأیید مدیر نمایش داده می‌شود/);assert.match(editor,/moderationStatus!=="APPROVED"/)});
test("admin moderation lists status and provides approve reject only",()=>{assert.match(adminApi,/\/api\/admin\/reviews/);assert.match(adminApi,/approveReview/);assert.match(adminApi,/rejectReview/);assert.match(admin,/reviewerDisplayName/);assert.match(admin,/businessName/);assert.match(admin,/moderationStatus/);assert.match(admin,/تأیید/);assert.match(admin,/رد/);assert.doesNotMatch(adminApi,/DELETE|adminRemove/)});
test("public review lists are compact and progressively disclosed",()=>{assert.match(section,/slice\(0,visibleCount\)/);assert.match(products,/slice\(0,visibleCount\)/);assert.match(section,/نمایش نظرات بیشتر/);assert.match(css,/padding: 12px 14px/);assert.match(css,/line-height: 1\.65/)});
