package com.foody.reviews.service;

import com.foody.businesses.entity.*; import com.foody.businesses.service.*; import com.foody.common.exception.*; import com.foody.menus.entity.Menu; import com.foody.menus.service.MenuService; import com.foody.products.entity.Product; import com.foody.products.service.ProductService; import com.foody.reviews.dto.*; import com.foody.reviews.entity.*; import com.foody.reviews.repository.*; import com.foody.users.entity.*; import com.foody.users.service.UserService;
import java.math.*; import java.util.*; import java.util.function.Function; import java.util.stream.Collectors; import org.springframework.dao.DataIntegrityViolationException; import org.springframework.security.access.AccessDeniedException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
class ProductReviewServiceImpl implements ProductReviewService {
 private static final int MAX_COMMENT_LENGTH=2000;
 private final ProductReviewRepository reviews; private final ReviewRepository businessReviews; private final ProductService products; private final MenuService menus; private final BusinessService businesses; private final UserService users;
 ProductReviewServiceImpl(ProductReviewRepository r,ReviewRepository br,ProductService p,MenuService m,BusinessService b,UserService u){reviews=r;businessReviews=br;products=p;menus=m;businesses=b;users=u;}
 @Transactional(readOnly=true) public ProductReviewListResponse list(Long productId){Target t=approvedTarget(productId);List<ProductReview> found=reviews.findByProductIdOrderByCreatedAtDescIdDesc(t.product().getId());Map<Long,User> people=people(found.stream().map(ProductReview::getReviewerUserId).toList());ReviewRatingSummary s=reviews.summarize(productId);BigDecimal avg=s.getAverageRating()==null?BigDecimal.ZERO.setScale(2):BigDecimal.valueOf(s.getAverageRating()).setScale(2,RoundingMode.HALF_UP);return new ProductReviewListResponse(found.stream().map(r->ProductReviewResponse.from(r,person(people,r.getReviewerUserId()).getFullName())).toList(),avg,s.getReviewCount());}
 @Transactional(readOnly=true) public ProductReviewResponse mine(Long productId,Long reviewerId){requireReviewerTarget(productId,reviewerId);return response(owned(productId,reviewerId));}
 @Transactional public ProductReviewResponse create(Long productId,Long reviewerId,ReviewRequest request){requireReviewerTarget(productId,reviewerId);validate(request);if(reviews.existsByProductIdAndReviewerUserId(productId,reviewerId))throw duplicate();ProductReview r=new ProductReview();r.setProductId(productId);r.setReviewerUserId(reviewerId);apply(r,request);try{return response(reviews.saveAndFlush(r));}catch(DataIntegrityViolationException e){throw duplicate();}}
 @Transactional public ProductReviewResponse update(Long productId,Long reviewerId,ReviewRequest request){requireReviewerTarget(productId,reviewerId);validate(request);ProductReview r=owned(productId,reviewerId);apply(r,request);return response(reviews.saveAndFlush(r));}
 @Transactional public void delete(Long productId,Long reviewerId){requireReviewerTarget(productId,reviewerId);reviews.delete(owned(productId,reviewerId));}
 @Transactional public void deleteForAdmin(Long id){reviews.delete(reviews.findById(id).orElseThrow(()->new ResourceNotFoundException("Product review not found: "+id)));}
 @Transactional(readOnly=true) public OwnerReviewsResponse ownerReviews(Long ownerId){Business b=businesses.findByOwnerUserId(ownerId).orElseThrow(()->new ResourceNotFoundException("No business found for this owner"));List<Review> br=businessReviews.findByBusinessIdOrderByCreatedAtDescIdDesc(b.getId());List<Product> ownedProducts=menus.findMyMenus(ownerId).stream().flatMap(m->products.findMyProducts(ownerId,m.getId()).stream()).toList();Map<Long,Product> productMap=ownedProducts.stream().collect(Collectors.toMap(Product::getId,Function.identity()));List<ProductReview> pr=productMap.isEmpty()?List.of():reviews.findByProductIdInOrderByCreatedAtDescIdDesc(productMap.keySet());List<Long> ids=new ArrayList<>();br.forEach(r->ids.add(r.getCustomerUserId()));pr.forEach(r->ids.add(r.getReviewerUserId()));Map<Long,User> people=people(ids);return new OwnerReviewsResponse(br.stream().map(r->ReviewResponse.from(r,person(people,r.getCustomerUserId()).getFullName())).toList(),pr.stream().map(r->new OwnerProductReviewResponse(r.getId(),r.getProductId(),productMap.get(r.getProductId()).getName(),r.getRating(),r.getComment(),person(people,r.getReviewerUserId()).getFullName(),r.getCreatedAt(),r.getUpdatedAt())).toList());}
 private Target approvedTarget(Long productId){Product p=products.findById(productId).orElseThrow(()->new ResourceNotFoundException("Product not found: "+productId));Menu m=menus.findById(p.getMenuId()).orElseThrow(()->new ResourceNotFoundException("Menu not found: "+p.getMenuId()));Business b=businesses.findByIdAndStatus(m.getBusinessId(),BusinessStatus.APPROVED).orElseThrow(()->new ResourceNotFoundException("Business not found: "+m.getBusinessId()));return new Target(p,b);}
 private void requireReviewerTarget(Long productId,Long reviewerId){User u=users.findById(reviewerId).orElseThrow(()->new ResourceNotFoundException("Reviewer not found"));if(u.getRole()!=UserRole.CUSTOMER&&u.getRole()!=UserRole.BUSINESS_OWNER)throw new AccessDeniedException("Only customers and business owners may review products");Target t=approvedTarget(productId);CustomerBusinessAccessPolicy.requireNotOwnedBy(reviewerId,t.business());}
 private ProductReview owned(Long pid,Long uid){return reviews.findByProductIdAndReviewerUserId(pid,uid).orElseThrow(()->new ResourceNotFoundException("Product review not found for this reviewer"));}
 private ProductReviewResponse response(ProductReview r){return ProductReviewResponse.from(r,users.findById(r.getReviewerUserId()).orElseThrow(()->new ResourceNotFoundException("Reviewer not found")).getFullName());}
 private Map<Long,User> people(Collection<Long> ids){return users.findAllById(ids.stream().distinct().toList()).stream().collect(Collectors.toMap(User::getId,Function.identity()));}
 private User person(Map<Long,User> map,Long id){User u=map.get(id);if(u==null)throw new ResourceNotFoundException("Reviewer not found");return u;}
 private static void validate(ReviewRequest r){if(r==null||r.rating()==null||r.rating()<1||r.rating()>5)throw new InvalidRequestException("Rating must be an integer from 1 to 5");if(r.comment()!=null&&r.comment().trim().length()>MAX_COMMENT_LENGTH)throw new InvalidRequestException("Comment must not exceed 2000 characters");}
 private static void apply(ProductReview r,ReviewRequest q){r.setRating(q.rating());String c=q.comment();r.setComment(c==null||c.isBlank()?null:c.trim());}
 private static DuplicateResourceException duplicate(){return new DuplicateResourceException("You have already reviewed this product; update your existing review instead");}
 private record Target(Product product,Business business){}
}
