package com.foody.reviews;
import static org.assertj.core.api.Assertions.*; import com.foody.AbstractContainerBaseTest; import com.foody.businesses.entity.*; import com.foody.businesses.repository.BusinessRepository; import com.foody.common.exception.*; import com.foody.menus.entity.Menu; import com.foody.menus.repository.MenuRepository; import com.foody.products.entity.Product; import com.foody.products.repository.ProductRepository; import com.foody.reviews.dto.*; import com.foody.reviews.entity.ReviewModerationStatus; import com.foody.reviews.service.ProductReviewService; import com.foody.reviews.service.ReviewModerationService; import com.foody.users.entity.*; import com.foody.users.repository.UserRepository; import java.math.BigDecimal; import java.util.*; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.security.access.AccessDeniedException;
class ProductReviewIntegrationTest extends AbstractContainerBaseTest {
 @Autowired ProductReviewService reviews; @Autowired ReviewModerationService moderation; @Autowired UserRepository users; @Autowired BusinessRepository businesses; @Autowired MenuRepository menus; @Autowired ProductRepository products;
 User customer,other,owner,otherOwner,admin;Business business,otherBusiness;Product product,otherProduct;
 @BeforeEach void setup(){customer=user(UserRole.CUSTOMER);other=user(UserRole.CUSTOMER);owner=user(UserRole.BUSINESS_OWNER);otherOwner=user(UserRole.BUSINESS_OWNER);admin=user(UserRole.ADMIN);business=business(owner);otherBusiness=business(otherOwner);product=product(business);otherProduct=product(otherBusiness);}
 @Test void customerCreatesEditsDeletesAndAggregateTracksOnlyApproved(){ProductReviewResponse created=reviews.create(product.getId(),customer.getId(),new ReviewRequest(4,"  good  "));assertThat(created.comment()).isEqualTo("good");assertThat(created.moderationStatus()).isEqualTo(ReviewModerationStatus.PENDING);assertThat(reviews.list(product.getId()).reviewCount()).isZero();moderation.moderate("PRODUCT",created.id(),ReviewModerationStatus.APPROVED);assertThat(reviews.list(product.getId())).extracting(ProductReviewListResponse::reviewCount,ProductReviewListResponse::averageRating).containsExactly(1L,new BigDecimal("4.00"));assertThat(reviews.update(product.getId(),customer.getId(),new ReviewRequest(2,"ok")).moderationStatus()).isEqualTo(ReviewModerationStatus.PENDING);assertThat(reviews.list(product.getId()).reviewCount()).isZero();reviews.delete(product.getId(),customer.getId());}
 @Test void duplicatePerReviewerAndProductIsRejected(){reviews.create(product.getId(),customer.getId(),new ReviewRequest(5,null));assertThatThrownBy(()->reviews.create(product.getId(),customer.getId(),new ReviewRequest(4,null))).isInstanceOf(DuplicateResourceException.class);reviews.create(otherProduct.getId(),customer.getId(),new ReviewRequest(3,null));}
 @Test void businessOwnerReviewsOtherProductButNotOwn(){reviews.create(otherProduct.getId(),owner.getId(),new ReviewRequest(5,"great"));assertThat(reviews.mine(otherProduct.getId(),owner.getId()).rating()).isEqualTo(5);assertThatThrownBy(()->reviews.create(product.getId(),owner.getId(),new ReviewRequest(5,null))).isInstanceOf(AccessDeniedException.class);}
 @Test void unrelatedUserCannotMutateReview(){reviews.create(product.getId(),customer.getId(),new ReviewRequest(5,null));assertThatThrownBy(()->reviews.update(product.getId(),otherOwner.getId(),new ReviewRequest(1,null))).isInstanceOf(ResourceNotFoundException.class);}
 @Test void adminCannotCreateButCanModerate(){assertThatThrownBy(()->reviews.create(product.getId(),admin.getId(),new ReviewRequest(5,null))).isInstanceOf(AccessDeniedException.class);Long id=reviews.create(product.getId(),customer.getId(),new ReviewRequest(5,null)).id();moderation.moderate("PRODUCT",id,ReviewModerationStatus.APPROVED);assertThat(reviews.list(product.getId()).reviewCount()).isEqualTo(1);}
 @Test void publicResponseHasNoPrivateIdentity(){assertThat(Arrays.stream(ProductReviewResponse.class.getRecordComponents()).map(java.lang.reflect.RecordComponent::getName)).containsExactly("id","rating","comment","reviewerDisplayName","moderationStatus","createdAt","updatedAt");}
 @Test void ownerDashboardSeparatesBusinessAndProductReviews(){Long id=reviews.create(product.getId(),customer.getId(),new ReviewRequest(5,"item")).id();assertThat(reviews.ownerReviews(owner.getId()).productReviews()).isEmpty();moderation.moderate("PRODUCT",id,ReviewModerationStatus.APPROVED);OwnerReviewsResponse result=reviews.ownerReviews(owner.getId());assertThat(result.businessReviews()).isEmpty();assertThat(result.productReviews()).singleElement().satisfies(r->{assertThat(r.productName()).isEqualTo(product.getName());assertThat(r.reviewerDisplayName()).isEqualTo(customer.getFullName());});}
 private User user(UserRole role){User u=new User();u.setEmail(UUID.randomUUID()+"@product-review.test");u.setFullName("Reviewer "+role);u.setPasswordHash("unused");u.setRole(role);return users.saveAndFlush(u);}private Business business(User owner){Business b=new Business();b.setOwnerUserId(owner.getId());b.setName("Business "+UUID.randomUUID());b.setBusinessType("CAFE");b.setStatus(BusinessStatus.APPROVED);return businesses.saveAndFlush(b);}private Product product(Business b){Menu m=new Menu();m.setBusinessId(b.getId());m.setName("Menu");m=menus.saveAndFlush(m);Product p=new Product();p.setMenuId(m.getId());p.setName("Product "+UUID.randomUUID());p.setPrice(BigDecimal.TEN);return products.saveAndFlush(p);}
}
